# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/auth/auth.proto\x12\x04\x61uth\"-\n\x10PlainTextMessage\x12\x19\n\x11plaintext_message\x18\x01 \x01(\t\"/\n\x14ReturnEncryptionInfo\x12\x17\n\x0f\x65ncryption_info\x18\x01 \x01(\t2N\n\x04\x41uth\x12\x46\n\x0eShowEncryption\x12\x16.auth.PlainTextMessage\x1a\x1a.auth.ReturnEncryptionInfo\"\x00\x42-Z+github.com/ease-lab/vSwarm-proto/proto/authb\x06proto3')



_PLAINTEXTMESSAGE = DESCRIPTOR.message_types_by_name['PlainTextMessage']
_RETURNENCRYPTIONINFO = DESCRIPTOR.message_types_by_name['ReturnEncryptionInfo']
PlainTextMessage = _reflection.GeneratedProtocolMessageType('PlainTextMessage', (_message.Message,), {
  'DESCRIPTOR' : _PLAINTEXTMESSAGE,
  '__module__' : 'proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.PlainTextMessage)
  })
_sym_db.RegisterMessage(PlainTextMessage)

ReturnEncryptionInfo = _reflection.GeneratedProtocolMessageType('ReturnEncryptionInfo', (_message.Message,), {
  'DESCRIPTOR' : _RETURNENCRYPTIONINFO,
  '__module__' : 'proto.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.ReturnEncryptionInfo)
  })
_sym_db.RegisterMessage(ReturnEncryptionInfo)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/ease-lab/vSwarm-proto/proto/auth'
  _PLAINTEXTMESSAGE._serialized_start=31
  _PLAINTEXTMESSAGE._serialized_end=76
  _RETURNENCRYPTIONINFO._serialized_start=78
  _RETURNENCRYPTIONINFO._serialized_end=125
  _AUTH._serialized_start=127
  _AUTH._serialized_end=205
# @@protoc_insertion_point(module_scope)
