# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/rnn_serving/rnn_serving.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/rnn_serving/rnn_serving.proto\x12\x0brnn_serving\"4\n\x0cSendLanguage\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x12\n\nnumSamples\x18\x02 \x01(\x05\"\x1c\n\tGetString\x12\x0f\n\x07message\x18\x01 \x01(\t2S\n\nRNNServing\x12\x45\n\x0eGenerateString\x12\x19.rnn_serving.SendLanguage\x1a\x16.rnn_serving.GetString\"\x00\x42<Z:github.com/vhive-serverless/vSwarm-proto/proto/rnn_servingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.rnn_serving.rnn_serving_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:github.com/vhive-serverless/vSwarm-proto/proto/rnn_serving'
  _globals['_SENDLANGUAGE']._serialized_start=52
  _globals['_SENDLANGUAGE']._serialized_end=104
  _globals['_GETSTRING']._serialized_start=106
  _globals['_GETSTRING']._serialized_end=134
  _globals['_RNNSERVING']._serialized_start=136
  _globals['_RNNSERVING']._serialized_end=219
# @@protoc_insertion_point(module_scope)
