// MIT License

// Copyright (c) 2021 EASE Lab

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: proto/rnn_serving/rnn_serving.proto

package rnn_serving

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RNNServing_GenerateString_FullMethodName = "/rnn_serving.RNNServing/GenerateString"
)

// RNNServingClient is the client API for RNNServing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RNNServingClient interface {
	GenerateString(ctx context.Context, in *SendLanguage, opts ...grpc.CallOption) (*GetString, error)
}

type rNNServingClient struct {
	cc grpc.ClientConnInterface
}

func NewRNNServingClient(cc grpc.ClientConnInterface) RNNServingClient {
	return &rNNServingClient{cc}
}

func (c *rNNServingClient) GenerateString(ctx context.Context, in *SendLanguage, opts ...grpc.CallOption) (*GetString, error) {
	out := new(GetString)
	err := c.cc.Invoke(ctx, RNNServing_GenerateString_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RNNServingServer is the server API for RNNServing service.
// All implementations must embed UnimplementedRNNServingServer
// for forward compatibility
type RNNServingServer interface {
	GenerateString(context.Context, *SendLanguage) (*GetString, error)
	mustEmbedUnimplementedRNNServingServer()
}

// UnimplementedRNNServingServer must be embedded to have forward compatible implementations.
type UnimplementedRNNServingServer struct {
}

func (UnimplementedRNNServingServer) GenerateString(context.Context, *SendLanguage) (*GetString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateString not implemented")
}
func (UnimplementedRNNServingServer) mustEmbedUnimplementedRNNServingServer() {}

// UnsafeRNNServingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RNNServingServer will
// result in compilation errors.
type UnsafeRNNServingServer interface {
	mustEmbedUnimplementedRNNServingServer()
}

func RegisterRNNServingServer(s grpc.ServiceRegistrar, srv RNNServingServer) {
	s.RegisterService(&RNNServing_ServiceDesc, srv)
}

func _RNNServing_GenerateString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLanguage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RNNServingServer).GenerateString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RNNServing_GenerateString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RNNServingServer).GenerateString(ctx, req.(*SendLanguage))
	}
	return interceptor(ctx, in, info, handler)
}

// RNNServing_ServiceDesc is the grpc.ServiceDesc for RNNServing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RNNServing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rnn_serving.RNNServing",
	HandlerType: (*RNNServingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateString",
			Handler:    _RNNServing_GenerateString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rnn_serving/rnn_serving.proto",
}
