# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fibonacci/fibonacci.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/fibonacci/fibonacci.proto\x12\tfibonacci\"-\n\x10PlainTextMessage\x12\x19\n\x11plaintext_message\x18\x01 \x01(\t\"/\n\x14ReturnEncryptionInfo\x12\x17\n\x0f\x65ncryption_info\x18\x01 \x01(\t2]\n\tFibonacci\x12P\n\x0eShowEncryption\x12\x1b.fibonacci.PlainTextMessage\x1a\x1f.fibonacci.ReturnEncryptionInfo\"\x00\x42\x32Z0github.com/ease-lab/vSwarm-proto/proto/fibonaccib\x06proto3')



_PLAINTEXTMESSAGE = DESCRIPTOR.message_types_by_name['PlainTextMessage']
_RETURNENCRYPTIONINFO = DESCRIPTOR.message_types_by_name['ReturnEncryptionInfo']
PlainTextMessage = _reflection.GeneratedProtocolMessageType('PlainTextMessage', (_message.Message,), {
  'DESCRIPTOR' : _PLAINTEXTMESSAGE,
  '__module__' : 'proto.fibonacci.fibonacci_pb2'
  # @@protoc_insertion_point(class_scope:fibonacci.PlainTextMessage)
  })
_sym_db.RegisterMessage(PlainTextMessage)

ReturnEncryptionInfo = _reflection.GeneratedProtocolMessageType('ReturnEncryptionInfo', (_message.Message,), {
  'DESCRIPTOR' : _RETURNENCRYPTIONINFO,
  '__module__' : 'proto.fibonacci.fibonacci_pb2'
  # @@protoc_insertion_point(class_scope:fibonacci.ReturnEncryptionInfo)
  })
_sym_db.RegisterMessage(ReturnEncryptionInfo)

_FIBONACCI = DESCRIPTOR.services_by_name['Fibonacci']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/ease-lab/vSwarm-proto/proto/fibonacci'
  _PLAINTEXTMESSAGE._serialized_start=46
  _PLAINTEXTMESSAGE._serialized_end=91
  _RETURNENCRYPTIONINFO._serialized_start=93
  _RETURNENCRYPTIONINFO._serialized_end=140
  _FIBONACCI._serialized_start=142
  _FIBONACCI._serialized_end=235
# @@protoc_insertion_point(module_scope)
