# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compression.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ompression.proto\x12\x0b\x63ompression\"\x18\n\x08SendFile\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x11GetCompressedFile\x12\x0f\n\x07message\x18\x01 \x01(\t2W\n\x0c\x46ileCompress\x12G\n\x0c\x43ompressFile\x12\x15.compression.SendFile\x1a\x1e.compression.GetCompressedFile\"\x00\x42<Z:github.com/vhive-serverless/vSwarm-proto/proto/compressionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compression_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/vhive-serverless/vSwarm-proto/proto/compression'
  _globals['_SENDFILE']._serialized_start=34
  _globals['_SENDFILE']._serialized_end=58
  _globals['_GETCOMPRESSEDFILE']._serialized_start=60
  _globals['_GETCOMPRESSEDFILE']._serialized_end=96
  _globals['_FILECOMPRESS']._serialized_start=98
  _globals['_FILECOMPRESS']._serialized_end=185
# @@protoc_insertion_point(module_scope)
