// MIT License

// Copyright (c) 2021 EASE Lab

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: proto/video_processing/video_processing.proto

package video_processing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VideoProcessing_ConvertToGrayscale_FullMethodName = "/video_processing.VideoProcessing/ConvertToGrayscale"
)

// VideoProcessingClient is the client API for VideoProcessing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoProcessingClient interface {
	ConvertToGrayscale(ctx context.Context, in *SendVideo, opts ...grpc.CallOption) (*GetGrayscaleVideo, error)
}

type videoProcessingClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoProcessingClient(cc grpc.ClientConnInterface) VideoProcessingClient {
	return &videoProcessingClient{cc}
}

func (c *videoProcessingClient) ConvertToGrayscale(ctx context.Context, in *SendVideo, opts ...grpc.CallOption) (*GetGrayscaleVideo, error) {
	out := new(GetGrayscaleVideo)
	err := c.cc.Invoke(ctx, VideoProcessing_ConvertToGrayscale_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoProcessingServer is the server API for VideoProcessing service.
// All implementations must embed UnimplementedVideoProcessingServer
// for forward compatibility
type VideoProcessingServer interface {
	ConvertToGrayscale(context.Context, *SendVideo) (*GetGrayscaleVideo, error)
	mustEmbedUnimplementedVideoProcessingServer()
}

// UnimplementedVideoProcessingServer must be embedded to have forward compatible implementations.
type UnimplementedVideoProcessingServer struct {
}

func (UnimplementedVideoProcessingServer) ConvertToGrayscale(context.Context, *SendVideo) (*GetGrayscaleVideo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertToGrayscale not implemented")
}
func (UnimplementedVideoProcessingServer) mustEmbedUnimplementedVideoProcessingServer() {}

// UnsafeVideoProcessingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoProcessingServer will
// result in compilation errors.
type UnsafeVideoProcessingServer interface {
	mustEmbedUnimplementedVideoProcessingServer()
}

func RegisterVideoProcessingServer(s grpc.ServiceRegistrar, srv VideoProcessingServer) {
	s.RegisterService(&VideoProcessing_ServiceDesc, srv)
}

func _VideoProcessing_ConvertToGrayscale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVideo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoProcessingServer).ConvertToGrayscale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoProcessing_ConvertToGrayscale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoProcessingServer).ConvertToGrayscale(ctx, req.(*SendVideo))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoProcessing_ServiceDesc is the grpc.ServiceDesc for VideoProcessing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoProcessing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video_processing.VideoProcessing",
	HandlerType: (*VideoProcessingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertToGrayscale",
			Handler:    _VideoProcessing_ConvertToGrayscale_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/video_processing/video_processing.proto",
}
