# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/video_processing/video_processing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-proto/video_processing/video_processing.proto\x12\x10video_processing\"\x19\n\tSendVideo\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x11GetGrayscaleVideo\x12\x0f\n\x07message\x18\x01 \x01(\t2k\n\x0fVideoProcessing\x12X\n\x12\x43onvertToGrayscale\x12\x1b.video_processing.SendVideo\x1a#.video_processing.GetGrayscaleVideo\"\x00\x42\x41Z?github.com/vhive-serverless/vSwarm-proto/proto/video_processingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.video_processing.video_processing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z?github.com/vhive-serverless/vSwarm-proto/proto/video_processing'
  _globals['_SENDVIDEO']._serialized_start=67
  _globals['_SENDVIDEO']._serialized_end=92
  _globals['_GETGRAYSCALEVIDEO']._serialized_start=94
  _globals['_GETGRAYSCALEVIDEO']._serialized_end=130
  _globals['_VIDEOPROCESSING']._serialized_start=132
  _globals['_VIDEOPROCESSING']._serialized_end=239
# @@protoc_insertion_point(module_scope)
