# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import opt_125m_pb2 as opt__125m__pb2


class Opt125mBenchmarkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBenchmark = channel.unary_unary(
                '/opt125m.Opt125mBenchmark/GetBenchmark',
                request_serializer=opt__125m__pb2.Opt125mBenchmarkRequest.SerializeToString,
                response_deserializer=opt__125m__pb2.Opt125mBenchmarkReply.FromString,
                )


class Opt125mBenchmarkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBenchmark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Opt125mBenchmarkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBenchmark': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBenchmark,
                    request_deserializer=opt__125m__pb2.Opt125mBenchmarkRequest.FromString,
                    response_serializer=opt__125m__pb2.Opt125mBenchmarkReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'opt125m.Opt125mBenchmark', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Opt125mBenchmark(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBenchmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/opt125m.Opt125mBenchmark/GetBenchmark',
            opt__125m__pb2.Opt125mBenchmarkRequest.SerializeToString,
            opt__125m__pb2.Opt125mBenchmarkReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
