# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opt-125m.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eopt-125m.proto\x12\x07opt125m\"-\n\x17Opt125mBenchmarkRequest\x12\x12\n\nregenerate\x18\x01 \x01(\x08\"W\n\x15Opt125mBenchmarkReply\x12\x13\n\x0bmin_latency\x18\x01 \x01(\x03\x12\x13\n\x0bmax_latency\x18\x02 \x01(\x03\x12\x14\n\x0cmean_latency\x18\x03 \x01(\x03\x32\x66\n\x10Opt125mBenchmark\x12R\n\x0cGetBenchmark\x12 .opt125m.Opt125mBenchmarkRequest\x1a\x1e.opt125m.Opt125mBenchmarkReply\"\x00\x42\x39Z7github.com/vhive-serverless/vSwarm-proto/proto/opt-125mb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opt_125m_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7github.com/vhive-serverless/vSwarm-proto/proto/opt-125m'
  _globals['_OPT125MBENCHMARKREQUEST']._serialized_start=27
  _globals['_OPT125MBENCHMARKREQUEST']._serialized_end=72
  _globals['_OPT125MBENCHMARKREPLY']._serialized_start=74
  _globals['_OPT125MBENCHMARKREPLY']._serialized_end=161
  _globals['_OPT125MBENCHMARK']._serialized_start=163
  _globals['_OPT125MBENCHMARK']._serialized_end=265
# @@protoc_insertion_point(module_scope)
