# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpt-j.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgpt-j.proto\x12\x04gptj\"*\n\x14GPTJBenchmarkRequest\x12\x12\n\nregenerate\x18\x01 \x01(\x08\"T\n\x12GPTJBenchmarkReply\x12\x13\n\x0bmin_latency\x18\x01 \x01(\x03\x12\x13\n\x0bmax_latency\x18\x02 \x01(\x03\x12\x14\n\x0cmean_latency\x18\x03 \x01(\x03\x32W\n\rGPTJBenchmark\x12\x46\n\x0cGetBenchmark\x12\x1a.gptj.GPTJBenchmarkRequest\x1a\x18.gptj.GPTJBenchmarkReply\"\x00\x42\x36Z4github.com/vhive-serverless/vSwarm-proto/proto/gpt-jb\x06proto3')



_GPTJBENCHMARKREQUEST = DESCRIPTOR.message_types_by_name['GPTJBenchmarkRequest']
_GPTJBENCHMARKREPLY = DESCRIPTOR.message_types_by_name['GPTJBenchmarkReply']
GPTJBenchmarkRequest = _reflection.GeneratedProtocolMessageType('GPTJBenchmarkRequest', (_message.Message,), {
  'DESCRIPTOR' : _GPTJBENCHMARKREQUEST,
  '__module__' : 'gpt_j_pb2'
  # @@protoc_insertion_point(class_scope:gptj.GPTJBenchmarkRequest)
  })
_sym_db.RegisterMessage(GPTJBenchmarkRequest)

GPTJBenchmarkReply = _reflection.GeneratedProtocolMessageType('GPTJBenchmarkReply', (_message.Message,), {
  'DESCRIPTOR' : _GPTJBENCHMARKREPLY,
  '__module__' : 'gpt_j_pb2'
  # @@protoc_insertion_point(class_scope:gptj.GPTJBenchmarkReply)
  })
_sym_db.RegisterMessage(GPTJBenchmarkReply)

_GPTJBENCHMARK = DESCRIPTOR.services_by_name['GPTJBenchmark']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/vhive-serverless/vSwarm-proto/proto/gpt-j'
  _GPTJBENCHMARKREQUEST._serialized_start=21
  _GPTJBENCHMARKREQUEST._serialized_end=63
  _GPTJBENCHMARKREPLY._serialized_start=65
  _GPTJBENCHMARKREPLY._serialized_end=149
  _GPTJBENCHMARK._serialized_start=151
  _GPTJBENCHMARK._serialized_end=238
# @@protoc_insertion_point(module_scope)
