# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gpt_j_pb2 as gpt__j__pb2


class GPTJBenchmarkStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBenchmark = channel.unary_unary(
                '/gptj.GPTJBenchmark/GetBenchmark',
                request_serializer=gpt__j__pb2.GPTJBenchmarkRequest.SerializeToString,
                response_deserializer=gpt__j__pb2.GPTJBenchmarkReply.FromString,
                )


class GPTJBenchmarkServicer(object):
    """The greeting service definition.
    """

    def GetBenchmark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPTJBenchmarkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBenchmark': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBenchmark,
                    request_deserializer=gpt__j__pb2.GPTJBenchmarkRequest.FromString,
                    response_serializer=gpt__j__pb2.GPTJBenchmarkReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gptj.GPTJBenchmark', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GPTJBenchmark(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetBenchmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gptj.GPTJBenchmark/GetBenchmark',
            gpt__j__pb2.GPTJBenchmarkRequest.SerializeToString,
            gpt__j__pb2.GPTJBenchmarkReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
