# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/video_analytics_standalone/video_analytics_standalone.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAproto/video_analytics_standalone/video_analytics_standalone.proto\x12\x1avideo_analytics_standalone\"\x19\n\tSendVideo\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tGetResult\x12\x0f\n\x07message\x18\x01 \x01(\t2s\n\x0eVideoAnalytics\x12\x61\n\x0fObjectDetection\x12%.video_analytics_standalone.SendVideo\x1a%.video_analytics_standalone.GetResult\"\x00\x42KZIgithub.com/vhive-serverless/vSwarm-proto/proto/video_analytics_standaloneb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.video_analytics_standalone.video_analytics_standalone_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZIgithub.com/vhive-serverless/vSwarm-proto/proto/video_analytics_standalone'
  _globals['_SENDVIDEO']._serialized_start=97
  _globals['_SENDVIDEO']._serialized_end=122
  _globals['_GETRESULT']._serialized_start=124
  _globals['_GETRESULT']._serialized_end=152
  _globals['_VIDEOANALYTICS']._serialized_start=154
  _globals['_VIDEOANALYTICS']._serialized_end=269
# @@protoc_insertion_point(module_scope)
