# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.video_analytics_standalone import video_analytics_standalone_pb2 as proto_dot_video__analytics__standalone_dot_video__analytics__standalone__pb2


class VideoAnalyticsStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObjectDetection = channel.unary_unary(
                '/video_analytics_standalone.VideoAnalytics/ObjectDetection',
                request_serializer=proto_dot_video__analytics__standalone_dot_video__analytics__standalone__pb2.SendVideo.SerializeToString,
                response_deserializer=proto_dot_video__analytics__standalone_dot_video__analytics__standalone__pb2.GetResult.FromString,
                )


class VideoAnalyticsServicer(object):
    """The greeting service definition.
    """

    def ObjectDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoAnalyticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObjectDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.ObjectDetection,
                    request_deserializer=proto_dot_video__analytics__standalone_dot_video__analytics__standalone__pb2.SendVideo.FromString,
                    response_serializer=proto_dot_video__analytics__standalone_dot_video__analytics__standalone__pb2.GetResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_analytics_standalone.VideoAnalytics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoAnalytics(object):
    """The greeting service definition.
    """

    @staticmethod
    def ObjectDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/video_analytics_standalone.VideoAnalytics/ObjectDetection',
            proto_dot_video__analytics__standalone_dot_video__analytics__standalone__pb2.SendVideo.SerializeToString,
            proto_dot_video__analytics__standalone_dot_video__analytics__standalone__pb2.GetResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
