# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gptj.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngptj.proto\x12\x04gptj\"*\n\x14GptJBenchmarkRequest\x12\x12\n\nregenerate\x18\x01 \x01(\t\"*\n\x12GptJBenchmarkReply\x12\x14\n\x0clatency_info\x18\x01 \x01(\t2W\n\rGptJBenchmark\x12\x46\n\x0cGetBenchmark\x12\x1a.gptj.GptJBenchmarkRequest\x1a\x18.gptj.GptJBenchmarkReply\"\x00\x42\x35Z3github.com/vhive-serverless/vSwarm-proto/proto/gptjb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gptj_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/vhive-serverless/vSwarm-proto/proto/gptj'
  _globals['_GPTJBENCHMARKREQUEST']._serialized_start=20
  _globals['_GPTJBENCHMARKREQUEST']._serialized_end=62
  _globals['_GPTJBENCHMARKREPLY']._serialized_start=64
  _globals['_GPTJBENCHMARKREPLY']._serialized_end=106
  _globals['_GPTJBENCHMARK']._serialized_start=108
  _globals['_GPTJBENCHMARK']._serialized_end=195
# @@protoc_insertion_point(module_scope)
