// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gptj

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GptJBenchmarkClient is the client API for GptJBenchmark service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GptJBenchmarkClient interface {
	GetBenchmark(ctx context.Context, in *GptJBenchmarkRequest, opts ...grpc.CallOption) (*GptJBenchmarkReply, error)
}

type gptJBenchmarkClient struct {
	cc grpc.ClientConnInterface
}

func NewGptJBenchmarkClient(cc grpc.ClientConnInterface) GptJBenchmarkClient {
	return &gptJBenchmarkClient{cc}
}

func (c *gptJBenchmarkClient) GetBenchmark(ctx context.Context, in *GptJBenchmarkRequest, opts ...grpc.CallOption) (*GptJBenchmarkReply, error) {
	out := new(GptJBenchmarkReply)
	err := c.cc.Invoke(ctx, "/gptj.GptJBenchmark/GetBenchmark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GptJBenchmarkServer is the server API for GptJBenchmark service.
// All implementations must embed UnimplementedGptJBenchmarkServer
// for forward compatibility
type GptJBenchmarkServer interface {
	GetBenchmark(context.Context, *GptJBenchmarkRequest) (*GptJBenchmarkReply, error)
	mustEmbedUnimplementedGptJBenchmarkServer()
}

// UnimplementedGptJBenchmarkServer must be embedded to have forward compatible implementations.
type UnimplementedGptJBenchmarkServer struct {
}

func (UnimplementedGptJBenchmarkServer) GetBenchmark(context.Context, *GptJBenchmarkRequest) (*GptJBenchmarkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBenchmark not implemented")
}
func (UnimplementedGptJBenchmarkServer) mustEmbedUnimplementedGptJBenchmarkServer() {}

// UnsafeGptJBenchmarkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GptJBenchmarkServer will
// result in compilation errors.
type UnsafeGptJBenchmarkServer interface {
	mustEmbedUnimplementedGptJBenchmarkServer()
}

func RegisterGptJBenchmarkServer(s grpc.ServiceRegistrar, srv GptJBenchmarkServer) {
	s.RegisterService(&GptJBenchmark_ServiceDesc, srv)
}

func _GptJBenchmark_GetBenchmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GptJBenchmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GptJBenchmarkServer).GetBenchmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gptj.GptJBenchmark/GetBenchmark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GptJBenchmarkServer).GetBenchmark(ctx, req.(*GptJBenchmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GptJBenchmark_ServiceDesc is the grpc.ServiceDesc for GptJBenchmark service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GptJBenchmark_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gptj.GptJBenchmark",
	HandlerType: (*GptJBenchmarkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBenchmark",
			Handler:    _GptJBenchmark_GetBenchmark_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gptj.proto",
}
