// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/image_classification/image_classification.proto

package image_classification

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7accd682f3694294, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	MinLatency           int64    `protobuf:"varint,1,opt,name=min_latency,json=minLatency,proto3" json:"min_latency,omitempty"`
	MaxLatency           int64    `protobuf:"varint,2,opt,name=max_latency,json=maxLatency,proto3" json:"max_latency,omitempty"`
	MeanLatency          int64    `protobuf:"varint,3,opt,name=mean_latency,json=meanLatency,proto3" json:"mean_latency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7accd682f3694294, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMinLatency() int64 {
	if m != nil {
		return m.MinLatency
	}
	return 0
}

func (m *HelloReply) GetMaxLatency() int64 {
	if m != nil {
		return m.MaxLatency
	}
	return 0
}

func (m *HelloReply) GetMeanLatency() int64 {
	if m != nil {
		return m.MeanLatency
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "image_classification.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "image_classification.HelloReply")
}

func init() {
	proto.RegisterFile("proto/image_classification/image_classification.proto", fileDescriptor_7accd682f3694294)
}

var fileDescriptor_7accd682f3694294 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd0, 0x4b, 0x4b, 0x03, 0x31,
	0x10, 0x07, 0x70, 0x6b, 0xc5, 0xc7, 0xb4, 0xa7, 0xe0, 0x41, 0xbc, 0x58, 0x73, 0xf2, 0xd2, 0x5d,
	0x50, 0xfc, 0x02, 0x8a, 0xe8, 0xc1, 0xd3, 0xf6, 0x26, 0x48, 0x99, 0x86, 0xb1, 0x1d, 0xc8, 0x63,
	0x9b, 0xa4, 0xb1, 0xf9, 0xf6, 0x62, 0xba, 0x3e, 0x0e, 0xab, 0xb7, 0xf0, 0x9f, 0x1f, 0x61, 0xe6,
	0x0f, 0xb7, 0xad, 0x77, 0xd1, 0xd5, 0x6c, 0x70, 0x49, 0x73, 0xa5, 0x31, 0x04, 0x7e, 0x63, 0x85,
	0x91, 0x9d, 0xed, 0x0d, 0xab, 0xe2, 0xc5, 0x69, 0xdf, 0x4c, 0x4a, 0x18, 0x3f, 0x91, 0xd6, 0xae,
	0xa1, 0xf5, 0x86, 0x42, 0x14, 0x02, 0x0e, 0x2c, 0x1a, 0x3a, 0x1b, 0x4c, 0x06, 0x57, 0x27, 0x4d,
	0x79, 0xcb, 0x35, 0x40, 0x67, 0x5a, 0x9d, 0xc5, 0x05, 0x8c, 0x0c, 0xdb, 0xb9, 0xc6, 0x48, 0x56,
	0xe5, 0x02, 0x87, 0x0d, 0x18, 0xb6, 0xcf, 0xbb, 0xa4, 0x00, 0xdc, 0x7e, 0x83, 0xfd, 0x0e, 0xe0,
	0xf6, 0x0b, 0x5c, 0xc2, 0xd8, 0x10, 0xfe, 0x7c, 0x31, 0x2c, 0x62, 0xf4, 0x99, 0x75, 0xe4, 0xfa,
	0x15, 0x8e, 0x1e, 0x3d, 0x51, 0x24, 0x2f, 0x1a, 0x38, 0x9e, 0x61, 0x2e, 0x0b, 0x08, 0x59, 0xf5,
	0x1e, 0xf8, 0xfb, 0x82, 0xf3, 0xc9, 0xbf, 0xa6, 0xd5, 0x59, 0xee, 0xdd, 0x3d, 0xbc, 0xdc, 0x2f,
	0x39, 0xae, 0x36, 0x8b, 0x4a, 0x39, 0x53, 0xa7, 0x15, 0x27, 0x9a, 0x06, 0xf2, 0x89, 0xbc, 0xa6,
	0x10, 0xea, 0x34, 0x7b, 0x47, 0x6f, 0xa6, 0xbb, 0x9e, 0xff, 0x6e, 0x7b, 0x71, 0x58, 0x66, 0x37,
	0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x5f, 0x1b, 0xa7, 0x92, 0x01, 0x00, 0x00,
}
